"""Async wrapper over the Apify ``streamers/youtube-scraper`` actor.

One actor run per query: the query is submitted as ``searchQueries`` with
``downloadSubtitles`` on (plain-text), so a single run returns fully-enriched
video items — metadata, channel avatar, AND the transcript inline. Uses the
native ``ApifyClientAsync`` (available in ``apify-client``), so the whole call
is awaitable and overlaps under the scrape semaphore — no thread offload needed.

Running per query (rather than one run for all queries) preserves which query
surfaced each video, so ``source_queries`` / ``relevance_index`` stay accurate.

See: apify.com/streamers/youtube-scraper
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

# The actor and subtitle settings are properties of this integration, not config.
ACTOR_ID = "streamers/youtube-scraper"
SUBTITLES_FORMAT = "plaintext"  # so each item's transcript is plain text inline


class WorkerApifyClient:
    """Searches YouTube via the Apify scraper, subtitles included, per query."""

    def __init__(self, token: str) -> None:
        # Imported lazily so the module (and its testable callers) load without
        # the optional dependency; only an actual fetch needs it.
        from apify_client import ApifyClientAsync

        self._client = ApifyClientAsync(token)

    async def search(
        self, query: str, *, max_results: int, language: str
    ) -> list[dict]:
        """Run the actor for one query and return its dataset items raw.

        Subtitles ride along in each item (``downloadSubtitles``), so the result
        is the whole feed for this query — metadata + avatar + transcript."""
        logger.info("Apify search %r (max %d) via %s", query, max_results, ACTOR_ID)
        run = await self._client.actor(ACTOR_ID).call(
            run_input={
                "searchQueries": [query],
                "maxResults": max_results,
                "maxResultsShorts": 0,
                "maxResultStreams": 0,
                "sortingOrder": "relevance",
                "downloadSubtitles": True,
                "subtitlesFormat": SUBTITLES_FORMAT,
                "subtitlesLanguage": language,
                "preferAutoGeneratedSubtitles": True,
                "saveSubsToKVS": False,
            }
        )
        dataset_id = (
            run.get("defaultDatasetId")
            if isinstance(run, dict)
            else getattr(run, "default_dataset_id", None)
        )
        if not dataset_id:
            raise RuntimeError("Apify run did not return a dataset id")
        page = await self._client.dataset(dataset_id).list_items()
        return list(page.items)
