package user

import (
	"context"
)

// Repository defines the interface for user data access.
type Repository interface {
	Get(ctx context.Context, id string) (*UserResponse, error)
	GetByEmail(ctx context.Context, email string) (*UserResponse, error)
	List(ctx context.Context, limit, offset int32) ([]*UserResponse, error)
	Create(ctx context.Context, req *CreateUserRequest) (*UserResponse, error)
	Update(ctx context.Context, id string, req *UpdateUserRequest) (*UserResponse, error)
	Delete(ctx context.Context, id string) error
}

// repository implements the Repository interface.
// Once you run `sqlc generate`, uncomment and implement this.
//
// import "github.com/yourorg/combatden-api/internal/user/sql"
//
// type repository struct {
// 	queries *sql.Queries  // Generated by sqlc in ./sql/ subdirectory
// }
//
// func NewRepository(queries *sql.Queries) Repository {
// 	return &repository{queries: queries}
// }
//
// func (r *repository) Get(ctx context.Context, id string) (*UserResponse, error) {
// 	// Use r.queries.GetUser(ctx, uuid.MustParse(id))
// 	// Convert sql.User to UserResponse
// 	return nil, nil
// }
// ... implement other methods
