// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetGym(ctx context.Context, gymID pgtype.UUID) (Gym, error)
}

var _ Querier = (*Queries)(nil)
