// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJustName = `-- name: GetJustName :one
SELECT name, created_at
FROM users
WHERE id = $1
`

type GetJustNameRow struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetJustName(ctx context.Context, id pgtype.UUID) (GetJustNameRow, error) {
	row := q.db.QueryRow(ctx, getJustName, id)
	var i GetJustNameRow
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}

const getStuff = `-- name: GetStuff :one
SELECT id, email, name, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetStuff(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getStuff, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
