// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGym = `-- name: GetGym :one
SELECT gym_id, gym_name, owner_id FROM gyms
WHERE gym_id = $1
`

func (q *Queries) GetGym(ctx context.Context, gymID pgtype.UUID) (Gym, error) {
	row := q.db.QueryRow(ctx, getGym, gymID)
	var i Gym
	err := row.Scan(&i.GymID, &i.GymName, &i.OwnerID)
	return i, err
}
