"""VideoSpecService — append-only read/write for a gym's video spec.

DB-only (no Pydantic AI). Reads from ``gym_video_spec_latest`` (the view that
surfaces the most-recent version per gym); writes by appending a new row to
``gym_video_spec`` (the raw versioned table is never UPDATE'd).
"""

from __future__ import annotations

import json
from uuid import UUID

from schema.video import GymVideoSpecSource
from sqlalchemy import text

from src.shared.database import DirectDatabasePool
from src.shared.sql_loader import load_sql
from src.videos import SQL_DIR
from src.videos.schema.video_spec_schema import VideoSpecDraft, VideoSpecView


class VideoSpecService:
    """Read/write access to the append-only ``gym_video_spec`` table."""

    def __init__(self, *, db_pool: DirectDatabasePool) -> None:
        self._db = db_pool

    async def load_latest(self, gym_id: UUID) -> VideoSpecView | None:
        """The gym's latest spec version, or None when none exists yet."""
        sql = load_sql(SQL_DIR / "video_spec_load_latest.sql")
        async with self._db.session() as session:
            row = (
                (await session.execute(text(sql), {"gym_id": str(gym_id)}))
                .mappings()
                .fetchone()
            )
        return self._row_to_view(row) if row is not None else None

    async def save_version(
        self,
        gym_id: UUID,
        draft: VideoSpecDraft,
        queries: list[str],
        *,
        source: GymVideoSpecSource = GymVideoSpecSource.admin_update,
    ) -> VideoSpecView:
        """Append a new spec version from a criteria draft + generated queries.

        ``queries`` are passed separately (generated by ``VideoQueryGenerator``
        after the diff guard passes) rather than authored by the agent.
        """
        sql = load_sql(SQL_DIR / "video_spec_insert_version.sql")
        params = {
            "gym_id": str(gym_id),
            "gym_type": json.dumps([d.value for d in draft.disciplines]),
            "short_videos_desc": draft.short_videos_desc,
            "short_avoid_desc": draft.short_avoid_desc,
            "videos_desc": draft.videos_desc,
            "avoid_desc": draft.avoid_desc,
            "queries": json.dumps(queries),
            "source": source.value,
            "imported_from": None,
        }
        async with self._db.session() as session, session.begin():
            row = (
                (await session.execute(text(sql), params)).mappings().fetchone()
            )
        return self._row_to_view(row)

    # ── helpers ─────────────────────────────────────────────────

    def _row_to_view(self, row: object) -> VideoSpecView:
        data = dict(row)  # type: ignore[arg-type]
        data["disciplines"] = self._as_list(data.pop("gym_type"))
        data["queries"] = self._as_list(data.get("queries"))
        return VideoSpecView.model_validate(data)

    @staticmethod
    def _as_list(value: object) -> list:
        """A JSONB column as a Python list — tolerant of the driver returning
        either a decoded list or the raw JSON string."""
        if value is None:
            return []
        if isinstance(value, str):
            return json.loads(value)
        return value
