linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - unused
    - misspell
    - unconvert
    - unparam
    - gosimple
    - gocritic
    - revive

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  errcheck:
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam

run:
  timeout: 5m
  tests: true
