linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosec
    - ineffassign
    - unused
    - misspell
    - unconvert
    - unparam
    - gosimple
    - gocritic
    - revive

  exclusions:
    paths:
      # Exclude the vendor directory if you are using vendored dependencies
      - vendor
      # Exclude specific directories using regular expressions
      - ^test/
      - pkg

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
