"""Thin wrapper over the Apify ``streamers/youtube-scraper`` actor.

One actor run per query: we submit the query as ``searchQueries`` with
``downloadSubtitles`` on (plain-text), so a single run returns fully-enriched
video items — metadata, channel avatar, AND the transcript inline — with no
separate stats/avatar/transcript calls. ``.call()`` blocks until the run
finishes (Apify polls) and the dataset items are returned raw; parsing lives in
``transform.py`` so it stays testable without the network.

Running per query (rather than one run for all queries) preserves which query
surfaced each video, so ``source_queries`` / ``relevance_index`` stay accurate.

See: apify.com/streamers/youtube-scraper
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

# The actor and subtitle settings are properties of this integration, not config.
ACTOR_ID = "streamers/youtube-scraper"
SUBTITLES_FORMAT = "plaintext"  # so each item's transcript is plain text inline


class ApifyYouTubeSearchClient:
    """Searches YouTube via the Apify scraper, subtitles included, per query."""

    def __init__(self, token: str) -> None:
        # Imported lazily so the scraper module (and its testable transform /
        # classify helpers) load without the optional `apify_client` dependency;
        # only an actual fetch needs it.
        from apify_client import ApifyClient

        self._client = ApifyClient(token)

    def search(
        self, query: str, *, max_results: int, language: str
    ) -> list[dict]:
        """Run the actor for one query and return its dataset items raw.

        Subtitles ride along in each item (``downloadSubtitles``), so the result
        is the whole feed for this query — metadata + avatar + transcript."""
        logger.info("Apify search %r (max %d) via %s", query, max_results, ACTOR_ID)
        run = self._client.actor(ACTOR_ID).call(
            run_input={
                "searchQueries": [query],
                "maxResults": max_results,
                "maxResultsShorts": 0,
                "maxResultStreams": 0,
                "sortingOrder": "relevance",
                "downloadSubtitles": True,
                "subtitlesFormat": SUBTITLES_FORMAT,
                "subtitlesLanguage": language,
                "preferAutoGeneratedSubtitles": True,
                "saveSubsToKVS": False,
            }
        )
        dataset_id = (
            run.get("defaultDatasetId")
            if isinstance(run, dict)
            else getattr(run, "default_dataset_id", None)
        )
        if not dataset_id:
            raise RuntimeError("Apify run did not return a dataset id")
        return list(self._client.dataset(dataset_id).iterate_items())
