DEFAULT_PASSWORD = "abcd1234"
# Seed for Python's `random` and Faker, set once at the top of seed().
SEED = 42
NUM_GYMS = 3
MEMBERS_PER_GYM = 100
REWARDS_PER_GYM = 4
EXTRA_EMPLOYEES_PER_GYM = 2
CLASSES_PER_GYM = 7
ACTIVITIES_PER_MEMBER = 5
HISTORY_DAYS = 30
